'seed':
  desc:
  value: 90
'gpus':
  desc:
  value: 1
'NUM_CS':
  desc:
  value: 1
'NUM_US':
  desc:
  value: 1
'NUM_DIST':
  desc:
  value: 10
'ISI_interval':
  desc:
  value: [7,13]
'ITI_interval':
  desc:
  value: [80,120]
'LEN_CS':
  desc:
  value: 4
'LEN_US':
  desc:
  value: 2
'LEN_DIST':
  desc:
  value: 4
'ADAMB1':
  desc:
  value: 0.9
'ADAMB2':
  desc:
  value: 0.999
'ADAME':
  desc:
  value: 10e-8
'LAMBDA':
  desc:
  value: 0
'N_TRAIN_STEPS':
  desc:
  value: 10000
'TBPTT_T':
  desc:
  value: 10
'HIDDEN_L_SIZE':
  desc:
  value: 10
'STEP_SIZE':
  desc:
  value: 1e-4
'INITIAL_STEPS':
  desc: Number of env steps to take and store before starting training
  value: 100
'GAMMA':
  desc: This is set in train.py
  value: 0
